### ISSUE TITLE
Execute decompressing dynamically

### ISSUE THREAD

**Issue by ArmandCom** [nayuki/Reference-Huffman-coding#5]
I couldn't find the way to decompress just a few lines of the compressed file. It gives an error as it doesn't find the EOF symbol that is added in the compression function. 

What i was trying was to split part of the compressed string and decompress this portion. I'm sure I got the wrong approach. How should it be done? 

Thanks

**Comment by nayuki** [comment]
Note: The question/comment you posted is not an "issue" with my reference Huffman coding library. The topic is about how to use the API to accomplish a specific task you want.

My advice:
* Don't split or touch the compressed bitstream data. This is considered advanced manipulation.
* Look at [HuffmanDecompress.decompress()](https://github.com/nayuki/Reference-Huffman-coding/blob/master/java/src/HuffmanDecompress.java#L62) and see how it decodes one symbol at a time. If you write or change the loop yourself, you can choose to stop decompressing at any point in time.
* Ask https://stackoverflow.com/ for any further questions, as this is a general-level question about basic data compression APIs, not a bug or problem with my library specifically.
